id: I090F1902
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-05T20:06:14.735521'
last_modified: '2022-06-05T20:06:14.735533'
parser: null
source_metadata:
  title: Tenth Pawo Rinpoche Series
  language: en
  description: 'Texts by and about the Tenth Pawo Rinpoche, Tsuklak Mawé Wangchuk
    (gtsug lag smra ba’i dbang phyug, 1912–1991):'
  volume:
    f97F2:
      title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
      base_file: f97F2.txt
      order: 1
      parent: Guru Yoga
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
